export const CHANGE_FONT_COLOR = 'CHANGE_FONT_COLOR'
export const CHANGE_BG_COLOR = 'CHANGE_BG_COLOR'
export const CHANGE_FONT_STYLE = 'CHANGE_FONT_STYLE'
export const CHANGE_FONT_SIZE = 'CHANGE_FONT_SIZE'
  